begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select plan(27);

insert into auth.users(instance_id,id,aud,role,email,created_at,updated_at) values
('00000000-0000-0000-0000-000000000000','15000000-0000-4000-8000-000000000001','authenticated','authenticated','ledger-manager@test.invalid',now(),now()),
('00000000-0000-0000-0000-000000000000','15000000-0000-4000-8000-000000000002','authenticated','authenticated','ledger-staff@test.invalid',now(),now());
insert into public.studios(id,name,slug) values('25000000-0000-4000-8000-000000000001','Ledger Modules','ledger-modules');
insert into public.studio_members(studio_id,user_id,display_name,roles,status,valid_from,valid_until,revoked_at) values
('25000000-0000-4000-8000-000000000001','15000000-0000-4000-8000-000000000001','Manager',array['studio_manager'],'active',now()-interval '1 day',null,null),
('25000000-0000-4000-8000-000000000001','15000000-0000-4000-8000-000000000002','Staff',array['photographer'],'active',now()-interval '1 day',null,null);

select ok(has_table_privilege('authenticated','public.erp_payroll_payments','SELECT'),'payroll projection has explicit authenticated SELECT');
select ok(not has_table_privilege('authenticated','public.erp_payroll_payments','INSERT'),'browser cannot insert payroll directly');
select ok(not has_table_privilege('authenticated','public.erp_cheques','INSERT'),'browser cannot insert cheque directly');
select ok(has_function_privilege('authenticated','public.record_payroll_payment(uuid,text,jsonb)','EXECUTE'),'payroll command is explicitly granted');
select ok(has_function_privilege('authenticated','public.transition_cheque(uuid,uuid,bigint,text,text,bigint)','EXECUTE'),'cheque lifecycle command is explicitly granted');

set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claim.sub','15000000-0000-4000-8000-000000000001',true);
select is((public.record_payroll_payment(
 '25000000-0000-4000-8000-000000000001','payroll-ledger-command-1',
 '{"personnelUserId":"15000000-0000-4000-8000-000000000002","periodMonth":"2026-08-01","grossIrr":100000,"deductionsIrr":20000,"bankId":"bank-main","expectedLedgerVersion":0}'::jsonb)->>'ok')::boolean,true,
 'payroll posts through its atomic server command');
select is((select count(*) from public.erp_payroll_payments),1::bigint,'one payroll aggregate is recorded');
select is((select net_irr from public.erp_payroll_payments),80000::bigint,'net payroll is generated by the database');
select is((select operation from public.finance_transactions where payload->>'personnelUserId'='15000000-0000-4000-8000-000000000002'),'record_withdrawal','payroll posts an authoritative withdrawal');
select is((select sum(debit_irr) from public.finance_journal_lines),(select sum(credit_irr) from public.finance_journal_lines),'payroll journal remains balanced');
select throws_ok($$select public.record_payroll_payment(
 '25000000-0000-4000-8000-000000000001','payroll-ledger-command-2',
 '{"personnelUserId":"15000000-0000-4000-8000-000000000002","periodMonth":"2026-08-01","grossIrr":100000,"deductionsIrr":0,"bankId":"bank-main","expectedLedgerVersion":1}'::jsonb)$$,
 '23505',null,'duplicate personnel period is rejected atomically');
select is((select count(*) from public.finance_transactions),1::bigint,'failed duplicate payroll leaves no finance transaction');

create temp table _cheque_result as select public.register_cheque(
 '25000000-0000-4000-8000-000000000001',
 '{"chequeNumber":"CHK-1","direction":"incoming","party":"Customer","amountIrr":50000,"bankId":"bank-main","dueDate":"2026-09-01"}'::jsonb) result;
select is((select result->>'status' from _cheque_result),'pending','new cheque starts pending without ledger recognition');
select is((select count(*) from public.finance_transactions),1::bigint,'registering a pending cheque does not change cash');
select throws_ok(format($q$select public.transition_cheque(
 '25000000-0000-4000-8000-000000000001','%s',1,'cleared','cheque-clear-wrong-version',0)$q$,
 (select result->>'chequeId' from _cheque_result)),
 '40001',null,'cheque clearing enforces ledger optimistic concurrency');
select is((select status from public.erp_cheques where id=(select (result->>'chequeId')::uuid from _cheque_result)),'pending','failed clearing leaves cheque pending');
select is((public.transition_cheque(
 '25000000-0000-4000-8000-000000000001',(select (result->>'chequeId')::uuid from _cheque_result),1,
 'cleared','cheque-clear-command-1',1)->>'status'),'cleared','clearing atomically recognizes cheque cash');
select is((select count(*) from public.finance_transactions),2::bigint,'clearing adds exactly one finance transaction');
select ok((select finance_transaction_id is not null from public.erp_cheques where id=(select (result->>'chequeId')::uuid from _cheque_result)),'cleared cheque links its finance transaction');
select is((select version from public.erp_cheques where id=(select (result->>'chequeId')::uuid from _cheque_result)),2::bigint,'cheque version increments on clearing');
select throws_ok(format($q$select public.transition_cheque(
 '25000000-0000-4000-8000-000000000001','%s',1,'cancelled','cheque-stale-command',2)$q$,
 (select result->>'chequeId' from _cheque_result)),
 '40001','cheque_version_conflict','stale cheque transition is rejected');
select is((public.transition_cheque(
 '25000000-0000-4000-8000-000000000001',(select (result->>'chequeId')::uuid from _cheque_result),2,
 'pending','cheque-reverse-command-1',2)->>'status'),'pending','cleared cheque can be reversed to pending through ledger command');
select ok((select finance_transaction_id is null and version=3 from public.erp_cheques
 where id=(select (result->>'chequeId')::uuid from _cheque_result)),'reversed cheque clears finance link and advances version');
select is((select sum(debit_irr) from public.finance_journal_lines),(select sum(credit_irr) from public.finance_journal_lines),'cheque clear and reversal preserve double-entry balance');
select is((select balance_irr from public.finance_account_balances where studio_id='25000000-0000-4000-8000-000000000001' and account_ref='asset:bank:bank-main'),(-80000)::bigint,'bank balance returns to payroll-only value after cheque reversal');

select set_config('request.jwt.claim.sub','15000000-0000-4000-8000-000000000002',true);
select is((select count(*) from public.erp_payroll_payments),1::bigint,'personnel can read only own payroll projection');
select is((select count(*) from public.erp_cheques),0::bigint,'non-finance personnel cannot read cheque projection');

select * from finish();
rollback;
